In [77]:
import numpy as np

In [78]:
## Create 2D array using [[]]
twoDArray = np.array([[5, 6, 7, 8], [15, 16, 17, 18], [25, 26, 27, 28], [35, 36, 37, 38]])
print(twoDArray)

[[ 5  6  7  8]
 [15 16 17 18]
 [25 26 27 28]
 [35 36 37 38]]


In [79]:
## Adds data as row
new_r_twoDArray = np.insert(twoDArray, 0, [[1, 2, 3, 4]], axis=0)
print(new_r_twoDArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [15 16 17 18]
 [25 26 27 28]
 [35 36 37 38]]


In [80]:
## Adds data as column
new_c_twoDArray = np.insert(twoDArray, 4, [[91, 92, 93, 94]], axis=1)
print(new_c_twoDArray)

[[ 5  6  7  8 91]
 [15 16 17 18 92]
 [25 26 27 28 93]
 [35 36 37 38 94]]


In [81]:
appended_2D = np.append(twoDArray, [[100, 101, 102, 103]], axis=0)
print(appended_2D)

[[  5   6   7   8]
 [ 15  16  17  18]
 [ 25  26  27  28]
 [ 35  36  37  38]
 [100 101 102 103]]


In [82]:
## Function that access the index of a 2D array
def access2DElement(array, rowIndex, columnIndex):
    if rowIndex >= len(array) or columnIndex >= len(array[0]):
        return('Index or column not found!')
    else:
        return(array[columnIndex][rowIndex])

access2DElement(appended_2D, 2, 3)

37

In [83]:
## Travesing 2D Array
def traverse2DArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])

traverse2DArray(appended_2D)

5
6
7
8
15
16
17
18
25
26
27
28
35
36
37
38
100
101
102
103


In [84]:
## Element Search in 2D Array

def search2DArray(array, target):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == target:
                return(f'The value is located at Column: {i}, Row: {j}')
    return('Value not found!')
            
search2DArray(appended_2D, 101)

'The value is located at Column: 4, Row: 1'

In [86]:
print(new_c_twoDArray)
deleting2DArray = np.delete(new_c_twoDArray, 4, axis=1)
print(deleting2DArray)

[[ 5  6  7  8 91]
 [15 16 17 18 92]
 [25 26 27 28 93]
 [35 36 37 38 94]]
[[ 5  6  7  8]
 [15 16 17 18]
 [25 26 27 28]
 [35 36 37 38]]
